api_config:
  qwen:
    client_type: "openai"
    qwen3-max:
      has_enable_thinking: False
    qwen-plus:
      has_enable_thinking: True
    qwen3-max-preview:
      has_enable_thinking: True
  deepseek:
    client_type: "openai"
    deepseek-v3:
      has_enable_thinking: False
    deepseek-v3.2:
      has_enable_thinking: False
    deepseek-r1:
      has_enable_thinking: True
  grok:
    client_type: "openai"
    grok-4-fast:
      has_enable_thinking: True
  gemini:
    client_type: "openai"
    gemini-2.5-pro:
      kwargs:
        reasoning_effort: "medium"
      has_enable_thinking: True
    gemini-2.5-flash:
      kwargs:
        reasoning_effort: "none"
      has_enable_thinking: False
  gpt:
    client_type: "openai"
    gpt-5.1:
      has_enable_thinking: True
  gpt-oss:
    client_type: "openai"
    gpt-oss-120b:
      model_name: "openai/gpt-oss-120b"
      kwargs:
        reasoning_effort: "low"
      has_enable_thinking: True
      